### PR TITLE
Sitecore search

### LINKED ISSUE #432: Sitecore Search - Preview Feedback
This is an open issue used to track the feedback from the preview of the Sitecore Search implementation on the developer portal.

Please leave any feedback you have in a comment below.

Note as comments below are address, either as fixed or spun out into a dedicated issue they will be hidden here to ensure we can track what is still outstanding.

### PR DESCRIPTION
**Pull request by robearlam**
Integration of Sitecore Search and removal of Coveo

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)

## Checklist:
- [x] I have read the Contributing guide.
- [x] My code/comments/docs fully adhere to the Code of Conduct.
- [x] My change is a code change.
- [ ] My change is a documentation change and there are NO other updates required.
- [ ] My change has new or updated images which are stored in the `/public/images` folder that need to be migrated to Sitecore DAM

Closes #432

### CODE REVIEW

**Review by jst-cyr — CHANGES_REQUESTED** [review]
I did not do exhaustive testing, but I tried to grab the most common places where search things fall over:

### ✅ TEST 1: Search for newsletter 'January'
1. Navigate to Newsletter archive (/newsletter)
2. In the search box at the top, type 'January' and press enter key
3. Filter by Developer Portal with Site Name

EXPECTED RESULT: January newsletters are top result
ACTUAL: As expected.

### ✅ TEST 2: UNCHECK Filter
1. From search results page, uncheck the Site Name filter for Developer Portal

EXPECTED RESULT: All matches that were previously shown should now be shown. Checkbox should appear unchecked
ACTUAL: As expected.

### ✅ TEST 3: Change sorting
1. Change sorting on right side drop-down from 'Suggested' to 'Title ASC'
2. Change sorting back to Suggested
3. Change sorting to 'Title DESC'
4. Change sorting to 'Title ASC'

EXPECTED RESULT: As the sorting is changed, the results should reorder to be ordered in the requested format. The selected sort option should remain selected.
ACTUAL: As expected

### ✅ TEST 4: Click on result
1. For any result, click on the entry

EXPECTED RESULT: Sent to the appropriate result page.
ACTUAL: As expected

### ⚠ TEST 5: Invalid search
1. In the search box, type an invalid keyword like 'januaryxdb' and press Enter key

EXPECTED RESULT: Message about no results should be displayed. Should not be able to navigate between pages. Filters should have no counts on them.
ACTUAL: Expected does occur for navigation and filters, but there is no message displayed about the lack of results and a strange '0' is shown on the screen where the "Showing [x] to [y]" results are supposed to be displayed.

### ✅ TEST 6: Filter by product
1. In the search box, type in 'personalization' and press Enter key
2. Go to the product filter and choose one option
3. Clear the first option
4. Go to the product filter and choose a second option
5. Clear the second option

EXPECTED RESULT: After every product selection is made, the filter should remember the selection. The results should update to only show results matching that product
ACTUAL: As expected, but it seems like there are only a few products available? I expected to see Personalize when searching for personalization. Are we not able to do something with the docs site where we infer the product from the slug?

### ✅ TEST 7: Navigation of results for lower page numbers
1. Select the arrow to jump to the next page
2. Select one of the page numbers displayed in the first (lower) block
4. Select the arrow to jump to the previous page
5. Refresh the search to be on page 1.
6. Press the '5' link to go to the 5th page
7. Press the right arrow to go to the next page '6'

EXPECTED: Arrows should navigate the user to the next/previous page of results. The 'current' page should be displayed in a different colour. Jumping directly to a page should show that page of results. Navigating beyond the first block of numbers should display the next block of numbers.
ACTUAL: As expected. Although, it seems odd that it shows first/last when in the early blocks of numbers, but only the middle block of numbers once you leave that block (i.e. go to page 6). I think this is probably the best we can do, it just seemed to change UX for some unknown reason.

### ❌ TEST 8: Navigation of results for higher page numbers
1. Search for 'personalization'. 
2. Select one of the numbers in the higher block (not the last)
3. Navigate to the next page
4. Navigate to the previous page
5. Select the very last page numbers

EXPECTED: Arrows should navigate the user to the next/previous page of results. The 'current' page should be displayed in a different colour. Jumping directly to a page should show that page of results. Navigating to the last page should show the final results.
ACTUAL: Navigation mostly functions, but very last page (417) displays no results and breaks the pagination. Displays the same as when there are no results.

### ❌ TEST 9: Special character search
1. Enter in '#$%?' as the search term

EXPECTED: No results, no errors, querystring is encoded
ACTUAL: Querystring does not encode the characters.

### ✅ TEST 10: Darkmode
1. From the first search results page, toggle dark mode on
2. Toggle dark mode off
3. Toggle dark mode on again
4. Navigate to another page of results.

EXPECTED: Display mode should adjust as requested by the user. It should persist through navigation
ACTUAL: As expected

### ⚠ TEST 11: Suggested terms
1. Type 'xdb' into the search bar but do not press enter
2. Click on a suggested result
3. Click on a suggested term

EXPECTED: Suggested results should display. Clicking on a result should navigate to that page. Clicking on a suggested term should run a search with that term.
ACTUAL: Mostly as expected, but clicking on a suggested term only changes the top results. It does not run the search.

**Comment by robearlam** [comment]
- ✅ **Test 5**: Fixed
- ⚠️**Test 8**: This is an issue with the API. When you perform a search that hits the 10,000 max doc return limit the last page errors. This has been passed to Product to investigate.
- ✅ **Test  9**: fixed
- ❓**Test 11**: I'm not sure what the issue is here, can you clarify?

**Comment by jst-cyr** [comment]
> ❓**Test 11**: I'm not sure what the issue is here, can you clarify?

The suggested results in the top search bar only show a few items. I expected that if I clicked on one of the suggested terms it would somehow allow me to run that search so I could see all the results for that term combination. 

For example, after typing in 'xdb' one of the suggested terms is 'xdb migration'. Clicking on it shows me a few results on the right-side, but there's no way for me to trigger that to be my search. I thought this was supposed to help with auto-completion of your search terms so you could run that search.

I might be completely missing the point of what is happening in the search bar, though.

**Comment by jst-cyr** [comment]
> ✅ **Test 5**: Fixed
> ✅ **Test 9**: fixed

Verified these two fixes.

**Comment by robearlam** [comment]
> > ❓**Test 11**: I'm not sure what the issue is here, can you clarify?
> 
> The suggested results in the top search bar only show a few items. I expected that if I clicked on one of the suggested terms it would somehow allow me to run that search so I could see all the results for that term combination.
> 
> For example, after typing in 'xdb' one of the suggested terms is 'xdb migration'. Clicking on it shows me a few results on the right-side, but there's no way for me to trigger that to be my search. I thought this was supposed to help with auto-completion of your search terms so you could run that search.
> 
> I might be completely missing the point of what is happening in the search bar, though.

Right, I get you now. This was also raised in the MVP feedback and is currently tracked in open issue #448

**Comment by robearlam** [comment]
As discussed with Test 8, i've changd the UX for the pagination to remove the shortcut to the last page.

I think that fixes everything raised and we can iterate on the rest after launch.

Are we good to merge now?

**Review by jst-cyr — APPROVED** [review]
Looks good! Let's merge!

**Pull request merged**
