### PR TITLE
Markdown improvements and architecture updates

### LINKED ISSUE #117: Ability to deeplink / autoscroll to partial groups rendered in GenericContentPage
We had a request from Pieter to be able to deep link / auto scroll to page sections rendered by the GenericContentPage component using #params in the url.

A good example is on the Learn page, it's quite large and it would be nice to be able to deep link to the Integrations section by doing something like https://developer-portal-sitecoretechnicalmarketing.vercel.app/learn#Integrations

### PR DESCRIPTION
**Pull request by markvanaalst**
## Description / Motivation
- Switched from react-markdown to next-mdx-remote
- Introducing (automatically generated) permalinks for h1-h6 in articles (fixes #117)
- Support for [oembed ](https://oembed.com/) within articles
- Configured ESLint and pre-commit checks for code consistency
- Restructured project

## How Has This Been Tested?
Local and on [Vercel](https://developer-portal-fc83gj1ug-sitecoretechnicalmarketing.vercel.app/)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)

## Checklist:
- [X] I have read the Contributing guide.
- [X] My code/comments/docs fully adhere to the Code of Conduct.
- [X] My change is a code change.
- [ ] My change is a documentation change and there are NO other updates required.
- [ ] My change has new or updated images which are stored in the `/public/images` folder that need to be migrated to Sitecore DAM

### CODE REVIEW

**Comment by markvanaalst** [comment]
#### 📝 Changed routes:


| [**/404**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/404) | [**/\[solution\]/\[product\]**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/[solution]/[product]) |
|:-:|:-:|
|<a href="https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/404">Screenshot of /404</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/W2N5PHIgpm3unCKseXCVBGHpRbdf3RV3OHgc6gCs8OQysVTgNNcYdMV1DvmoQcVmVmkR109wD-yicpTIwNKsJA.png">(view full size)</a> |<a href="https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/[solution]/[product]">Screenshot of /[solution]/[product]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/4ESZBHwcNNh_PT46x2gVbKxRyWl47fWCuE2IOxA_b4a94mBe_j5Ng36XSDBdULNYquA0FWllKFqlbG3HEvQWTg.png">(view full size)</a> |



| [**/\[solution\]**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/[solution]) | [**/community**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/community) |
|:-:|:-:|
|<a href="https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/[solution]">Screenshot of /[solution]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/IQtsALWCBzjCu8dDv5Jx-HaeI-aQreeZo_ugifuXYhcWlL_vZEUa-3met5VA7ly4xmMwbnBVvNnJwouCCel4FQ.png">(view full size)</a> |<a href="https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/community">Screenshot of /community</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/0_6DT-mNyfrxuDGnurbBwZ-Mn-4RyQdwzFDGrXptg-nsYvumQjKvgWUfh_10DJpd5K4QBGq0jFCqxXJhgYcZKA.png">(view full size)</a> |



| [**/contribute**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/contribute) | [**/discover**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/discover) |
|:-:|:-:|
|<a href="https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/contribute">Screenshot of /contribute</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/dX2wnKs4P2No6-Dn1uynLnKmYFd3mDhlJNiTDGzOTOpK-elsaWMX9Eg54lNpiya9dKZiuRRF5cjVhnqt2Z9FiQ.png">(view full size)</a> |<a href="https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/discover">Screenshot of /discover</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/GoLjQnmDda_jkGXys-qY857URjPIYiWLOuCHiHu1o24-c5TYjCDfDA2Fwx8NAI7-O4x6ytDcHPFkEZRx1ehBRg.png">(view full size)</a> |



And 18 other routes:
- [**/api/sitecore-community**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/api/sitecore-community)
- [**/docs**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/docs)
- [**/help**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/help)
- [**/**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/)
- [**/learn/faq/\[article\]/\[page\]**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/learn/faq/[article]/[page])
- [**/learn/faq/\[article\]**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/learn/faq/[article])
- [**/learn/getting-started/\[article\]**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/learn/getting-started/[article])
- [**/learn/getting-started**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/learn/getting-started)
- [**/learn**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/learn)
- [**/learn/integrations/\[integration\]**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/learn/integrations/[integration])
- [**/learn/integrations**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/learn/integrations)
- [**/newsletter/\[year\]/\[month\]**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/newsletter/[year]/[month])
- [**/newsletter/\[year\]**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/newsletter/[year])
- [**/newsletter**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/newsletter)
- [**/search**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/search)
- [**/trials/\[trial\]/\[parent\]/\[child\]**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/trials/[trial]/[parent]/[child])
- [**/trials/\[trial\]**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/trials/[trial])
- [**/trials**](https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app/trials)



Commit 0d96ef5cb064ed41b2516d8ce4cfaa351258abf1 (https://developer-portal-keqa1axnv-sitecoretechnicalmarketing.vercel.app).

**Review by jst-cyr — APPROVED** [review]
I've done a smoke test across most of the pages on the site, including articles, landing pages, integration guides, search, and validating links out still work and that the new 'inline link' feature gets you a working link.

This seems good enough to go forward with.  I couldn't see a page to test the MDX feature on, but the existing content seems fine so we can address that as new pages are introduced using the MDX embeds.

**Comment by jst-cyr** [comment]
@markvanaalst : I think the current site looks like it's working, but I'm not able to review the new MDX features. I have not done the merge until we can chat about whether there's a way to validate the MDX.

**Comment by markvanaalst** [comment]
Added two commits that show the improvements:
- [YouTube embed](https://developer-portal-eivonfr1h-sitecoretechnicalmarketing.vercel.app/learn/getting-started/introduction-to-composable-dxp#what-does-a-developer-need-to-know)
- [new line in (first) table](https://developer-portal-eivonfr1h-sitecoretechnicalmarketing.vercel.app/learn/faq/xm-personalize/features)

**Review by jst-cyr — APPROVED** [review]
Testing looks good, file changes look good (though there are a lot!) I approve for promotion to production.

**Pull request merged**
