### PR TITLE
Feature/connect product page

### PR DESCRIPTION
**Pull request by dylanyoung-dev**
## Description / Motivation

This change consists of two documentation changes.

First, this consists of the new Sitecore Connect product page.  I've added the new pages to the navigation, so the Solution tab has a new column for "Integrations" which then lists the "Sitecore Connect" page.  Where I could I link to the appropriate SSE, Community Forums, or YouTube playlist.  Under the Product section in the navigation I created a new section for "Sitecore Connect" and then a link to the product page with the title "Integration Platform".

Added the New Sitecore Connect FAQ Page.  This is linked to from the /learn page, the Getting Started with the Sitecore Composable DXP as well as from the Sitecore Connect product page.  It's based on Ahmed's Connect FAQ document.

The only concern I slightly had while working on this, is calling these integrations, which they are, given that there is an integrations section on the site.  Also, I'm not sure Connect would only involve the Composable story since I know there is talk about connectors for XP.  But for now, decided to keep this simple and not overcomplicate it.

## How Has This Been Tested?

I have tested this locally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)

## Checklist:

- [X] I have read the Contributing guide.
- [X] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change.
- [X] My change is a documentation change and there are NO other updates required.
- [ ] My change has new or updated images which are stored in the `/public/images` folder that need to be migrated to Sitecore DAM

### CODE REVIEW

**Comment by dylanyoung-dev** [comment]
Ahmed is currently reviewing the Sitecore Connect FAQ, but in the meantime, would love a review of this so that once Ahmed is happy, and the reviewers are happy with the list of changes I made, then we can get this document sent out publicly.

**Comment by jst-cyr** [comment]
> The complexities start arising when we look at adding the Marketplace link to the Integrations page (/integrations). 
I had not thought of the Integrations landing page, and did not remember that we had a limitation in what the link for one of the boxes there would be. From what I recall, it automatically generates those boxes, doesn't it? So right now we don't have a technical capability to show it there without a page. I get your comment now.

I think it's fine if the Marketplace doesn't show here on the Integrations page for now. But if you could raise that with @markvanaalst , perhaps there is a workaround I am not aware of. I think a page with a redirect could achieve the result, but likely not worth it for now. Having it in the menu should suffice.

> The second issue is the suggestion of adding the Sitecore Connect for *** products to the navigation and this page. Which presents the following issues:
> * There are 8 Sitecore Connect for *** products, which if I add them to the navigation would lead to 10 links, which is more links than anything else.  Is that okay? 

Agreed, too much, let's leave 'em off. But perhaps as a separate GithUb issue we can create a "Sitecore Connect for XP" page that has the links to the various connectors for XP? That might achieve our needs. But I think that's beyond the scope of this particular PR and should be a new issue. That should avoid the 8-page issue and fit with your suggestions around doing one page.

Let me know when you feel like things are ready for review!

**Comment by dylanyoung-dev** [comment]
> I think it's fine if the Marketplace doesn't show here on the Integrations page for now. But if you could raise that with @markvanaalst , perhaps there is a workaround I am not aware of. I think a page with a redirect could achieve the result, but likely not worth it for now. Having it in the menu should suffice.

I reviewed the source for that component, and it doesn't appear there is a way to add custom links to the component.  May be worth exploring a way to add that in the future.  We could also add markdown I believe under the component, but might be a little weird to suddenly have that.  But for now, will leave that off this PR.

> Agreed, too much, let's leave 'em off. But perhaps as a separate GitHub issue we can create a "Sitecore Connect for XP" page that has the links to the various connectors for XP? That might achieve our needs. But I think that's beyond the scope of this particular PR and should be a new issue. That should avoid the 8-page issue and fit with your suggestions around doing one page.

I'll go ahead and create a new Issue for that.  Another part of that is that in the Sitecore Connect insights chat, I saw this from Ivan: `we are currently deciding the future of many of our "Legacy" connectors such as Sitecore Connect for Salesforce CRM (SFCRM). This is an active ongoing process so I can't share any details or final decisions in this regard.` So I'm not sure if that means they are thinking of changing the name or removing the functionality, or nothing at all, but probably should wait to see the outcome of that as well.  For now, it'll be an issue and I'll wrap up this PR.

**Comment by dylanyoung-dev** [comment]
Created issue #373, and then the rest of the changes should be ready for review.

**Comment by jst-cyr** [comment]
Details of review of earlier issues below:

✅ 1. Missing marketplace link now in the menu

👍 2. Request for missing links on landing page dropped

✅ 3. Missing 'portal' link now on product page

✅ 4. Missing 'portal' link now on product page

✅ 5. Incorrect bolding on the FAQ 'General' page (/learn/faq/sitecore-connect/general) first sentence has been corrected.

✅ 6. In the 'Features and Capabilities' [considerations question](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/features#are-there-any-considerations-if-i-to-use-sitecore-connect-compared-to-if-i-license-workato-directly) "if I to use" now corrected to "if I use"

✅ 7. In the 'Features and Capabilities' [considerations question](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/features#are-there-any-considerations-if-i-to-use-sitecore-connect-compared-to-if-i-license-workato-directly) the term '3rdParty' has now been replaced by "third-party".

✅ 8. In the 'Features and Capabilities' [recipes question](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/features#will-sitecore-developed-connectors-and-recipes-be-available-for-all-workato-customers), the "Will Sitecore developed Connectors" is now corrected to "Sitecore-developed connectors"

✅ 9. In the 'Features and Capabilities' [which products](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/features#which-sitecore-products-will-you-develop-connectors-for) question the "January release"phrase now reads "January 2023"

✅ 10. The '3rdParty' issue is now corrected to "third-party" in [another question](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/features#can-i-use-connect-to-build-3rdparty-to-3rdparty-solutions)

✅ 11. The product name 'connect' now reads "Connect" in the final two questions of the ['Features and Capabilities' page](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/features)

✅ 12. On the 'Licensing' page, the [answer for how to license](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/licensing#how-to-license-sitecore-connect) the awkward phrasing has been corrected.

✅ 13. '3rdParty' fixed to "third-party" on the 'Licensing' page, the [answer for how to license](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/licensing#how-to-license-sitecore-connect) and other answers on the page.

✅ 14. In the ["how do you calculate the number of connections] question (https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/licensing#how-do-you-calculate-the-number-of-connections), the following issues were resolved:
* ✅ question now has "connections" instead of "Connections".
* ✅ "3rdParty" is now "third-party"
* ✅ "Sitecore Connections" is now "Sitecore connections"
* ✅ "tasks / Year" is now "tasks / year"
* ✅ "any overages" is now "Any overages"
* ✅ "additional Connection" likely should be "additional connection"

✅ 15. On several answers on the [licensing page](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/licensing) the word "Recipe" or "Task" is now fixed to "recipe" or "task"

✅ 16. On the 'Support Page' [question about how it works](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/support#how-shall-product-support-and-solutions-support-work-between-workato-and-sitecore), the word "Interactions" is now "interactions"

✅ 17. On the 'Support' page [question about how it works](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/support#how-shall-product-support-and-solutions-support-work-between-workato-and-sitecore), the text "How shall product support, and solutions support work between" now has the comma removed.

✅ 18. On the 'Support' page, the [timeline question](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/support#is-there-a-timeline-for-sitecore-products-to-support-sitecore-connect-with-connections-actions-and-scenarios) has multiple casing issues resolved:
* ✅ 'Sitecore Products' is now 'Sitecore products'
* ✅ 'support Sitecore connect' is now 'support Sitecore Connect'
* ✅ 'Product Teams' is now 'product teams'

✅ 19. On the 'Support' page, for the [documentation question](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/support#how-frequently-and-where-documentation-is-updated-for-product-connections-and-recipes-updates-documentation) the following was fixed:

* ✅'How frequently and where documentation is updated for product, connections, and Recipes updates documentation?' is now "Where will documentation updates for product, connections, and recipes be published?" 
* ✅ "Sitecore Connectors" is now "Sitecore connectors"
* ✅ "Recipes" is now "recipes"
* ✅ "Connections" is now "connections"
* ✅ "Connector" is now "connector"
* ✅ "Connection" is now "connection"

⚠ 20. In the ["Community" question](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/support#what-are-the-benefits-of-working-with-community-supported-platforms) the following fixes have been reviewed:
* ✅ First instance of "Community" corrected to "community"
* ❌ "Support" should be "support" (not fixed)

✅ 21. On the ["SLA" question](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/support#what-is-the-sla-and-uptime-guarantee-working-with-sitecore-connect) "Sitecore connect" has been fixed to "Sitecore Connect"

✅ 22. On the ["Data processing" question[(https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/support#where-is-integrated-data-being-processed-can-this-be-controlled-by-clients) the word "datacenters" is now using "data centers"

✅ 23. On the developer page, [what does it mean question](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/partners-developers#what-does-sitecore-connect-mean-for-developers-and-technicians):
* ✅ "Custom Connectors" is now "custom connectors"
* ✅ "Recipes" is now "recipes"
* ✅ "I recommend having a look" is now "It is recommended to have a look"

✅ 24. On the developer page, [advantage question](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/partners-developers#what-is-advantage-of-sitecore-connect-compared-to-azure-logic-zapier-or-other-ipaas-apps):
* ✅ "What is advantage" is now "What is the advantage"
* ✅ "Azure logic" is now "Azure Logic"
* ✅ "IPAAS" is now "iPaaS"
* ✅ "Recipes" is now "recipes"

✅ 25. On the developer page, [partner benefit question](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/partners-developers#sitecore-partners-position-their-own-integration-maintenance-how-sitecore-connect-benefit-them)     
* ✅ "How Sitecore Connect benefit them?" is now "How will Sitecore Connect benefit them?"
* ✅ "Recipes" is now "recipes"
* ✅ "throw creating" is now "by creating"
* ✅ Complicated run-on sentence has been simplified

**Review by jst-cyr — CHANGES_REQUESTED** [review]
After reviewing, I found only one issue that was not corrected:

⚠ In the ["Community" question](https://developer-portal-i43e7n1t3-sitecoretechnicalmarketing.vercel.app/learn/faq/sitecore-connect/support#what-are-the-benefits-of-working-with-community-supported-platforms):


❌ "Support" should be "support" (not fixed)

**Pull request merged**
