### PR TITLE
XM Cloud Tutorial: Changing tutorial page and structure

### PR DESCRIPTION
**Pull request by markvanaalst**
## Description / Motivation
Asking for feedback on this suggestion to change the markup for tutorials

[Test URL](https://developer-portal-git-feature-16596b-sitecoretechnicalmarketing.vercel.app/learn/getting-started/xm-cloud/tutorials/setup-xm-cloud)

New:
- Image component (click to enlarge functionality)
- Breadcrumbs
- Next/previous paging
- Split tutorial across different pages

## How Has This Been Tested?
Local and [Vercel](https://developer-portal-git-feature-16596b-sitecoretechnicalmarketing.vercel.app/learn/getting-started/xm-cloud/tutorials/setup-xm-cloud)

**Not fully tested yet**

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)

## Checklist:
- [X] I have read the Contributing guide.
- [X] My code/comments/docs fully adhere to the Code of Conduct.
- [X] My change is a code change.
- [ ] My change is a documentation change and there are NO other updates required.
- [ ] My change has new or updated images which are stored in the `/public/images` folder that need to be migrated to Sitecore DAM

### CODE REVIEW

**Comment by jst-cyr** [comment]
@markvanaalst : I like the image zoom-ins and the next/previous control for keeping the user flowing between the steps in the tutorial. We should definitely use that in the tutorials!

### Breadcrumb
I think I like the idea of the breadcrumb, but I'm having a hard time seeing how we make this work with what we are intending. In our intended structure, we have one XM Cloud beginner tutorial (maybe more in the future, but we shouldn't architect for that). So I'm wondering if we need that "XM Cloud Tutorials" level in the breadcrumb? Or is the idea that each tutorial we make would become like the "Setup XM Cloud" tutorial, at the top level? In my head we were going to create individual MD files for each step in the greater "tutorial" for getting started with XM Cloud.

Future state might look something like a tutorial called "Building your first XM Cloud project". Inside of that tutorial are multiple 'tutorials' that are part of an overall flow to go from nothing to "SUCCESS!":

- Setup XM Cloud infrastructure 
- Create a Site
- Create a Component
- Create a data source
- Deploy your project to production
- Add personalization

So in that scenario, I'm guessing the Breadcrumb would have something like "Create a site" at the lowest level (matching to a markdown) and then one level above it which is the overarching tutorial name.

`XM Cloud Tutorials > Building your first XM Cloud project > Create a Site`

For now, there would only be the one listed, but we can add extra tutorials in the future, I guess? Or just drop the 'XM Cloud Tutorials' piece for now in the breadcrumb until we get more tutorials.

### Left Navigation
Am I correct in saying that the current text that reads "Setup XM Cloud" there is driven by the manifest for the nav, so we can put anything there? (Like "Building your first XM Cloud project")

### Splitting tutorial into multiple pages
I actually have an open PR to split the current Setup MD into two (#731 ). We can split it more if needed, but we already would have those two plus two more that are in PRs. I think for our first take I would like to keep the MD files at an "accomplished goal" and not sub-divide lower than that, but I don't have any particular concern with splitting more. Let's see what it looks like once the current in-progress tutorials wrap up and we can split it up more if we need to.

**Review by jst-cyr — CHANGES_REQUESTED** [review]
@markvanaalst : I like the image zoom-ins and the next/previous control for keeping the user flowing between the steps in the tutorial. We should definitely use that in the tutorials!

Breadcrumb
I think I like the idea of the breadcrumb, but I'm having a hard time seeing how we make this work with what we are intending. In our intended structure, we have one XM Cloud beginner tutorial (maybe more in the future, but we shouldn't architect for that). So I'm wondering if we need that "XM Cloud Tutorials" level in the breadcrumb? Or is the idea that each tutorial we make would become like the "Setup XM Cloud" tutorial, at the top level? In my head we were going to create individual MD files for each step in the greater "tutorial" for getting started with XM Cloud.

Future state might look something like a tutorial called "Building your first XM Cloud project". Inside of that tutorial are multiple 'tutorials' that are part of an overall flow to go from nothing to "SUCCESS!":

Setup XM Cloud infrastructure
Create a Site
Create a Component
Create a data source
Deploy your project to production
Add personalization
So in that scenario, I'm guessing the Breadcrumb would have something like "Create a site" at the lowest level (matching to a markdown) and then one level above it which is the overarching tutorial name.

XM Cloud Tutorials > Building your first XM Cloud project > Create a Site

For now, there would only be the one listed, but we can add extra tutorials in the future, I guess? Or just drop the 'XM Cloud Tutorials' piece for now in the breadcrumb until we get more tutorials.

Left Navigation
Am I correct in saying that the current text that reads "Setup XM Cloud" there is driven by the manifest for the nav, so we can put anything there? (Like "Building your first XM Cloud project")

Splitting tutorial into multiple pages
I actually have an open PR to split the current Setup MD into two (https://github.com/Sitecore/developer-portal/pull/731 ). We can split it more if needed, but we already would have those two plus two more that are in PRs. I think for our first take I would like to keep the MD files at an "accomplished goal" and not sub-divide lower than that, but I don't have any particular concern with splitting more. Let's see what it looks like once the current in-progress tutorials wrap up and we can split it up more if we need to.

**Comment by markvanaalst** [comment]
Merged #731 into branch to get latest update and apply/configure components

**Comment by jst-cyr** [comment]
@markvanaalst : I've updated the manifest so the tutorials are in the correct order, but for some reason the index lists them in the opposite order? Or perhaps its in alphabetical order? Is there a way to have those cards be ordered in some way so that the tutorials are in the correct sequence on that listing page?

**Comment by markvanaalst** [comment]
Applied the menuOrder in frontmatter of the pages. Also made a minor change to the introduction of the articles to make it visually stand out.

PR is updated with the latest updates

**Comment by jst-cyr** [comment]
I've closed off some open pull requests and merged them into this one so that we are up to date. We should see about getting this PR close to finished and then merge it up so we can start pushing out our tutorials soon.

**Comment by jst-cyr** [comment]
@markvanaalst : I have updated this branch with the Create a Component tutorial and now we have our first package all together with the new visuals.

**Review by jst-cyr — CHANGES_REQUESTED** [review]
When going through the tutorial, I couldn't find the navigation to go to the next step. On pages where there are a lot of related documentation pages, the nav gets pushed off screen so the user will lose the flow as they finish a step. Is there a way to get it so that it more easily looks like they have another step to take to go forward? 

Do we need to move the 'related' stuff out to a separate component on the page?

**Comment by markvanaalst** [comment]
Extracting the 'related documentation' or moving the pagination up is hard to do and would likely mean we need to either break up the markdown or add the pagination component in the md file as a component. 

Instead I changed the "related documentation' to a unordered list and added a new component that is visually more present to navigate between tutorial pages on the bottom of the page. Please have a look and let me know what you think

**Review by jst-cyr — APPROVED** [review]
I love the latest visual changes that have been done. All the existing tutorials have been brought into line with each other and there is a nice flow between them. Looks great!

**Pull request merged**
