### PR TITLE
Extended Learn page to include integrations content

### PR DESCRIPTION
**Pull request by robearlam**
Added Integrations content under the learn section as discussed on Teams.

### CODE REVIEW

**Comment by markvanaalst** [comment]
Looks good!

One question though on URL structure, should we move integrations under the learn section (/learn/integrations/ instead of /integrations)?

**Review by jst-cyr — CHANGES_REQUESTED** [review]
Like Mark, I think we may want to update the URL structure, but I'm not tied to it if there's a strong reason for it.

I've made some minor text edits (fixing typos) in the original description. I've also made a suggestion for a new approach to the integration guide boxes.

Right now, there is one box, I assume intended for all guides. But the rest of the Learn page is all based on one box per product. I'm wondering if instead of having one blueprints.md file, instead we have an MD file for each product that has a guide? With the current guide, that would mean two boxes (one for Experience Manager and one for Sitecore CDP). This list can then grow as we have more guides, and each box gets filled out as we have more of the composable DXP covered.

What do you think?

**Comment by robearlam** [comment]
Yeah all of these suggestions make sense. 

- I've moved the integration pages to live under 'learn', this also involved moving the root learn page to live in a learn folder as the index for that root.
- I've also rolled out @jst-cyr's suggestion around product based panels, which makes sense. I feel like we might have a too many panels down the track but I dont think thats a problem we should solve till it actually becomes a problem!

Think this looks good to merge now?

**Review by markvanaalst — APPROVED** [review]
Great, let's merge!

**Pull request merged**
