### PR TITLE
Added Documentation for Connect

### PR DESCRIPTION
**Pull request by dylanyoung-dev**
## Description / Motivation

Adding the new Sitecore Connect documentation based on issue #379.  This is only a documentation update.

## How Has This Been Tested?

This was tested locally during development.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)

## Checklist:

- [x] I have read the Contributing guide.
- [x] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change.
- [x] My change is a documentation change and there are NO other updates required.
- [ ] My change has new or updated images which are stored in the `/public/images` folder that need to be migrated to Sitecore DAM

### CODE REVIEW

**Comment by dylanyoung-dev** [comment]
Added docs based on the description provided in #379, however not sure the implementation was the desired outcome, since I've added the integrations section, with one block for Sitecore Connect, with two links, one to documentation and the other to the integration guides.  Not sure it was intended that integration guides sit under the "Sitecore Connect" block?  Thoughts?

**Review by jst-cyr — CHANGES_REQUESTED** [review]
Hey @dylanyoung-dev , this is what I saw:
* The Sitecore Connect product page isn't listing Documentation as a separate section, so is out of sync with what is done on other product pages. For example, something like [Sitecore Discover](https://developer.sitecore.com/commerce/discover) or [XM Cloud](https://developers.sitecore.com/content-management/xm-cloud#documentation) . Note that there's a separate section for Documentation, and major pages that would be important to devs are called out in a list.
* For the Integrations page, I was thinking more that we would replicate the boxes we have on /learn/integrations, with the different products listed. However, thinking it through now, I do see how having each one as their own box on both Learn and Docs starts getting messy. Let's just leave the integration guides off for now to make it easier.

**Comment by dylanyoung-dev** [comment]
Alright @jst-cyr, I've updated with your comments.

**Review by jst-cyr — APPROVED** [review]
Looks good!

**Pull request merged**
