### PR TITLE
Added StackExchange API MVP.

### PR DESCRIPTION
**Pull request by bhgeorge**
StackExchange called during SSR

### CODE REVIEW

**Comment by bhgeorge** [comment]
TODO: need to test the tags part of the api again... got rate limited before I could actually test what's in the product here...

**Comment by andershopkins** [comment]
I've confirmed that tags are working as inteded.

e.g. `stackexchange: ['#sxa']`:

```
[
  {
    tags: [ 'sxa', 'solr', 'jss' ],
    owner: {
      account_id: 9236206,
      reputation: 111,
      user_id: 5681,
      user_type: 'registered',
      profile_image: 'https://lh4.googleusercontent.com/-pbSbU33-QQk/AAAAAAAAAAI/AAAAAAAAAQM/cNJ3_O-k6GE/photo.jpg?sz=128',
      display_name: 'Nikola Kramaric',
      link: 'https://sitecore.stackexchange.com/users/5681/nikola-kramaric'
    },
    is_answered: true,
    view_count: 81,
    accepted_answer_id: 29703,
    answer_count: 2,
    score: 1,
    last_activity_date: 1631128468,
    creation_date: 1626097997,
    last_edit_date: 1626179079,
    question_id: 29240,
    content_license: 'CC BY-SA 4.0',
    link: 'https://sitecore.stackexchange.com/questions/29240/visualization-getrenderings-returns-empty-string-using-local-data-source',
    title: 'Visualization.GetRenderings returns empty string using local: data source'
  },
  {
    tags: [ 'sxa', 'powershell-extensions', 'presentation' ],
    owner: {
      account_id: 15909865,
      reputation: 26,
      user_id: 5502,
      user_type: 'registered',
      profile_image: 'https://www.gravatar.com/avatar/1317b02e1848fb0eef63f52f5665fbfe?s=128&d=identicon&r=PG&f=1',
      display_name: 'Philippe B&#233;nard',
      link: 'https://sitecore.stackexchange.com/users/5502/philippe-b%c3%a9nard'
    },
    is_answered: false,
    view_count: 61,
    closed_date: 1631101680,
    answer_count: 1,
    score: 0,
    last_activity_date: 1631099250,
    creation_date: 1587024093,
    question_id: 24931,
    link: 'https://sitecore.stackexchange.com/questions/24931/sxa-missing-variants-in-a-cloned-rendering',
    closed_reason: 'Not suitable for this site',
    title: 'SXA Missing Variants in a cloned rendering'
  },
  {
    tags: [ 'sxa', 'sxa-cli' ],
    owner: {
      account_id: 334778,
      reputation: 13450,
      user_id: 135,
      user_type: 'moderator',
      accept_rate: 100,
      profile_image: 'https://i.stack.imgur.com/LUjc7.jpg?s=128&g=1',
      display_name: 'jammykam',
      link: 'https://sitecore.stackexchange.com/users/135/jammykam'
    },
    is_answered: false,
    view_count: 151,
    answer_count: 1,
    score: 2,
    last_activity_date: 1631095680,
    creation_date: 1586916327,
    question_id: 24909,
    content_license: 'CC BY-SA 4.0',
    link: 'https://sitecore.stackexchange.com/questions/24909/unable-to-upload-files-with-larger-than-100kb-using-creative-exchange-cli',
    title: 'Unable to upload files with larger than 100kb using Creative Exchange/CLI'
  }
]
```

**Review by andershopkins — APPROVED** [review]

**Comment by andershopkins** [comment]
@bhgeorge  merge conflicts to resolve, thank you.

**Review by andershopkins — CHANGES_REQUESTED** [review]
Please resolve merge conflicts @bhgeorge , also I suck at Github - I'll get better, promsie.

**Review by andershopkins — APPROVED** [review]

**Pull request merged**
