### PR TITLE
Fixes #215 - Broken links on XM-CDP integration

### LINKED ISSUE #215: Broken links on XM/CDP integration page
Due to moving the CDP documentation to the Sitecore documentation site the links on [this page](https://developers.sitecore.com/learn/integrations/xm-cdp) are broken

### PR DESCRIPTION
**Pull request by markvanaalst**
URLs that linked to the old Boxever documentation page where no longer working

## Description
Changed all URLs old Boxever documentation to new CDP documentation on doc.sitecore.com

## Motivation
Fixes #215 

## How Has This Been Tested?
Local testing and [Vercel preview environment](https://developer-portal-bzbnba8y2-sitecoretechnicalmarketing.vercel.app/learn/integrations/xm-cdp)

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)

## Checklist:
- [X] I have read the Contributing guide.
- [X] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change.
- [X] My change is a documentation change and there are NO other updates required.
- [ ] My change is a documentation change and it requires an update to the navigation.
- [ ] My change has new or updated images which are stored in the `/public/images` folder that need to be migrated to Sitecore DAM

### CODE REVIEW

**Review by jst-cyr — CHANGES_REQUESTED** [review]
There appears to still be a link about external data pointing to developer.boxever.com on the page. All the other links seem to work.

Side note: Based on the commit comparisons, it looks like more than the links were changed in this commit. There is a significant amount of text changed in the integration guide as well. Has this been validated with somebody that this new text is the correct version of text to go with these new links?

**Comment by markvanaalst** [comment]
Fixed the developer.boxever.com link

> Side note: Based on the commit comparisons, it looks like more than the links were changed in this commit. There is a significant amount of text changed in the integration guide as well. Has this been validated with somebody that this new text is the correct version of text to go with these new links?

This text originates from the integration guide hosted on the [CDP Knowledge Hub](https://sitecore.cdpknowledgehub.com/docs/integrating-experience-manager-with-sitecore-cdp} which already has the updated links

**Comment by jst-cyr** [comment]
I've added @robearlam on the review list here to finish off review. The links look good to me, but @robearlam should double-check that the new version of the text taken from the CDP KB version is indeed the correct version of the text.

**Review by jst-cyr — APPROVED** [review]

**Comment by robearlam** [comment]
I was unaware that the CDp Knowledge Hub had been updated, but it makes sense for us to keep them aligned 👍

(This should probably start a conversation about the content living in two places, should the developer portal be the true home, or the Knowledge hub?)

**Comment by jst-cyr** [comment]
@robearlam can you set that chat up with @markvanaalst and whomever we need from the CDP side to decide on this? My impression was that CDP KB was temporary only until the portal was launched.

**Pull request merged**
