### PR TITLE
Develop to Main - Navigation, Tooling, Cleanup, MVP APIs for Social Feeds

### PR DESCRIPTION
**Pull request by andershopkins**
**This PR includes:**

- The Navigation component UI and functionality, including separating the data for navigation into `/data`.
- The addition of `react-id-generator` so we can generate unique IDs that are SSR friendly in the component lifecycle, allowing for easier a11y and valid HTML.
- Code cleanup, including: using pascal case for components, using the new `@/` alias for imports
- Additional tooling, including prettier/lint-staged
- Addition of helpers, including dynamic tag for a11y considerations
- MVP APIs for Stackoverflow and Twitter

**Note**: Because PR also includes basic editorconfig/prettier + a manually installed githook (which has been noted in the `readme.md`, there are a larger number of changes that are formatting-only.

### CODE REVIEW

**Comment by andershopkins** [comment]
Fixed the Typescript compilation errors, going to add a `npx tsc` check in our commit hooks.

**Review by thomas-desmond — COMMENTED** [review]
image

Getting the above error for temp/develop-8-9-21 branch after pulling, running npm i, and then running dev. Is it unhappy that _app.js does not exist and is now a tsx?

**Review by jst-cyr — CHANGES_REQUESTED** [review]
The Twitter component does not seem to be showing up on the Docs page. The current 'production' shows this component:

image

But the branch version in Vercel does not have a Twitter component showing.

**Comment by bhgeorge** [comment]
@jst-cyr The TwitterFeed component was a quick implementation using the unauthenticated API to pull in a quick feed. This version of the API doesn't allow for feeds based on hashtags or feeds based on multiple parameters. We are currently blocked on a re-implementation of this based on having an API key to be able to query for the feed that we actually want.

In the mean time I had added some console warnings denoting the failing of the component in its current state. If you'd like we can revert the changes made at this point, or we can just wait until we have the API key and can do the real implementation.

**Comment by jst-cyr** [comment]
> @jst-cyr The TwitterFeed component was a quick implementation using the unauthenticated API to pull in a quick feed. This version of the API doesn't allow for feeds based on hashtags or feeds based on multiple parameters. We are currently blocked on a re-implementation of this based on having an API key to be able to query for the feed that we actually want.
> 
> In the mean time I had added some console warnings denoting the failing of the component in its current state. If you'd like we can revert the changes made at this point, or we can just wait until we have the API key and can do the real implementation.

I completely get the limitation on not pulling hashtags, or multiple parameters, but some of these (like /docs) have only one parameter and it's an account. Shouldn't those work?

**Comment by andershopkins** [comment]
> image
> 
> Getting the above error for temp/develop-8-9-21 branch after pulling, running npm i, and then running dev. Is it unhappy that _app.js does not exist and is now a tsx?

@thomas-desmond  -  this is a strange one, though I don't think it has anything to do with that.
https://github.com/vercel/next.js/blob/9b09b92a1443c34a33c85c452e93dc93f3d966cf/packages/next/build/webpack/config/blocks/css/messages.ts#L9

You can see that the error Next throws will always display `pages/_app.js` regardless.

**Questions**
- What version of node are you guys running?
- Windows?

I ask because there is `engine-strict=true` is now being enforced so if you're not within the node versions boundaries, `npm i` will run, look like it completes, and the bail out if you're using the wrong version (this is a Windows-only behavior).  On linux/macos it will bail out immediately.

There is some noise on Github about Tailwind 2.2.x and Next 11.x, but all signs point to the error to be with `node_modules`.

**Comment by bhgeorge** [comment]
@jst-cyr There was an issue in my code, accidentally had something inside of an if that shouldn't have been. Pushed an update.

**Comment by jst-cyr** [comment]
> @jst-cyr There was an issue in my code, accidentally had something inside of an if that shouldn't have been. Pushed an update.

@bhgeorge : Twitter API is showing on the pages that have accounts specified now! We'll need to unblock for the hashtags with an API key.

**Comment by thomas-desmond** [comment]
> > image
> > Getting the above error for temp/develop-8-9-21 branch after pulling, running npm i, and then running dev. Is it unhappy that _app.js does not exist and is now a tsx?
> 
> @thomas-desmond - this is a strange one, though I don't think it has anything to do with that.
> https://github.com/vercel/next.js/blob/9b09b92a1443c34a33c85c452e93dc93f3d966cf/packages/next/build/webpack/config/blocks/css/messages.ts#L9
> 
> You can see that the error Next throws will always display `pages/_app.js` regardless.
> 
> **Questions**
> 
> * What version of node are you guys running?
> * Windows?
> 
> I ask because there `engine-strict=true` is now being enforced, so if you're not within the node versions boundaries, `npm i` will run, look like it completes, and the bail out if you're using the wrong version (this is a Windows-only behavior, on linux/macos it will bail out immediately - it's strange).
> 
> There is some noise on Github about Tailwind 2.2.x and Next 11.x, but all signs point to the error to be with CSS libraries importing from `node_modules`.

Node version 14.17.4 and yes Windows. 

I completely deleted node modules, ran npm i again, the npm i was successful adding 606 packages. But still running into the same error.

**Comment by andershopkins** [comment]
> Node version 14.17.4 and yes Windows.
> 
> I completely deleted node modules, ran npm i again, the npm i was successful adding 606 packages. But still running into the same error.
> 
> Removing the following line from _app.tsx does get rid of the error but obviously then their are no styles for pages.
> import '@/styles/global.css';


Hmm, a bit at a loss. I can only reproduce the error if I do obviously wrong things like purposefully moving the `import` to anywhere else but `_app.tsx`.  

It also seems to be something particular with Windows as the nix-like environments are not having the issue (e.g. the Vercel build is deploying as expected and macOs is working as expected, using both `dev` and `build` commands).

```
  └ css/0d70e3c9e37ab38eb662.css                              3.83 kB
  ```

We will try on some alternative, Windows machines to see if we can reproduce and hone in on whatever the issue is.

In the meantime, are there any additional log in your shell?

**Comment by jst-cyr** [comment]
> > Node version 14.17.4 and yes Windows.
> In the meantime, are there any additional log in your shell?

Not sure if it helps, @andershopkins , but I am similarly running windows, but with Node 14.17.5. Same error. The terminal in VS Code shows the same as on the page, no additional details.

`npm run build` hits the same issue, no additional details.

**Comment by thomas-desmond** [comment]
> > Node version 14.17.4 and yes Windows.
> > I completely deleted node modules, ran npm i again, the npm i was successful adding 606 packages. But still running into the same error.
> > Removing the following line from _app.tsx does get rid of the error but obviously then their are no styles for pages.
> > import '@/styles/global.css';
> 
> Hmm, a bit at a loss. I can only reproduce the error if I do obviously wrong things like purposefully moving the `import` to anywhere else but `_app.tsx`.
> 
> It also seems to be something particular with Windows as the nix-like environments are not having the issue (e.g. the Vercel build is deploying as expected and macOs is working as expected, using both `dev` and `build` commands).
> 
> ```
>   └ css/0d70e3c9e37ab38eb662.css                              3.83 kB
> ```
> 
> We will try on some alternative, Windows machines to see if we can reproduce and hone in on whatever the issue is.
> 
> In the meantime, are there any additional log in your shell?

Like Jason mentioned, logs in shell are same as error. 

image

Not super helpful but I did try changing _app.tsx back to a .js. Same error but funny that it essentially says move all global css imports to where they are.

**Review by jst-cyr — APPROVED** [review]

**Comment by jst-cyr** [comment]
Just a note here that I approved the changes for the Twitter feed part (which seems to work now). The other issue is still outstanding, am I correct?

**Comment by andershopkins** [comment]
> Just a note here that I approved the changes for the Twitter feed part (which seems to work now). The other issue is still outstanding, am I correct?

@jst-cyr  thanks for the approval. @kylelengling is spinning up a windows machine right now to see if we can reproduce you and @thomas-desmond's problems with the global css import error in `_app.tsx`.

**Comment by jst-cyr** [comment]
Hey @andershopkins and @kylelengling , it appears this was a Windows-only issue introduced in Next v11.1.1. It is supposed to be resolved in Next v11.1.2. 

I have just committed the upgrade changes into this branch, and it looks like build is working for me on this end. If you can make a quick check that things are still all good on MacOSX, I think we'll be good to merge!

**Comment by andershopkins** [comment]
> Hey @andershopkins and @kylelengling , it appears this was a Windows-only issue introduced in Next v11.1.1. It is supposed to be resolved in Next v11.1.2.
> 
> I have just committed the upgrade changes into this branch, and it looks like build is working for me on this end. If you can make a quick check that things are still all good on MacOSX, I think we'll be good to merge!

@jst-cyr  - Confirmed `dev` and `build` tasks run as expected locally after updating to Next `11.1.2`.

**Comment by jst-cyr** [comment]
Merging initial APIs, navigation, tooling, and cleanup to the Main branch

**Pull request merged**
