### PR TITLE
Applying rebranding

### PR DESCRIPTION
**Pull request by markvanaalst**
## Description
Applying the new branding to the developer portal

## Motivation
Updating since the new branding has been released earlier this week

## How Has This Been Tested?
Locally and via [Vercel preview environment](https://developer-portal-fm679om3q-sitecoretechnicalmarketing.vercel.app/)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)

## Checklist:
- [X] I have read the Contributing guide.
- [X] My code/comments/docs fully adhere to the Code of Conduct.
- [X] My change is a code change.
- [ ] My change is a documentation change and there are NO other updates required.
- [ ] My change is a documentation change and it requires an update to the navigation.
- [ ] My change has new or updated images which are stored in the `/public/images` folder that need to be migrated to Sitecore DAM

### CODE REVIEW

**Review by jst-cyr — CHANGES_REQUESTED** [review]
I've only reviewed the home page because I suspect a lot of these need to be looked at before I continue looking at other pages.

1. In Dark mode, the current production uses the 'white' Sitecore logo (white characters for the word SITECORE). In the new rebranding, this is displaying as black on the dark menu. We should be swapping to the white logo in dark mode (as we do in prod currently).
2. The "arrow" icons used for call-to-action links has been updated from red to violet. This doesn't contrast enough on the dark background. The sitecore.com site seems to use both (red in the menu, but violet in pages). I think this needs to stay red (though likely the new red) in order to work on the dark background, or we need to flip it depending on whether it is dark mode or not (i.e. violet for light mode, red for dark mode)
3. On the homepage, News and Announcements and Latest blog posts hover-over link colour is still teal. (However, it shows up better on the dark background than the teal, see next feedback)
4. In the mobile menu, the hover-link colour is now violet (correct) but it doesn't contrast well on the charcoal. The 'burger' and 'x' icons are fine, but the words become hard to read. I think the teal worked better on the dark background. Conversely, the violet works better on the light background, so I would suggest we swap these when switching to dark mode.
5. The video 'hover' color goes to violet for the play button which is neat, but they don't seem to have done this on sitecore.com. I'm not sure this is an actual issue, just wanted to point it out. I like it, and while the contrast is not great, I don't think there's a better option since we can't know what the thumbnail will look like.
6. We no longer have a hero image on the home page. I like the banner look though, with the dark Sitecore logo. Very cool.
7. In production, the "Explore Sitecore by solution" goes to a slightly lighter charcoal, but in the new branding the lighter is a LOT lighter. Do we have something in between? It seems to be too light. Current prod uses a dark charcoal for the boxes, with the light charcoal as a border, and then an in-between charcoal for the panel background. The new brand seems to be using the same colour for the box border and the panel background.
8. The SSE component is showing the tag boxes in violet now, but the text is a very light violet or something else that is not contrasting well. The old white on teal contrasted better. If I click and hold, then slide my mouse it switches it to a better contrast. We probably just need to put the text to white.
9. On hovering over an SSE tag, it is swapping from violet box to white box. Looks decent, but doesn't match to the behaviour we had before (which went from dark teal to lighter teal)
10. The footer in dark mode is showing in white, instead of using the dark mode version (see prod for how it behaves now)

**Comment by jst-cyr** [comment]
Hey @markvanaalst , I can see new commits but the build seems to be failinlg. I tried rerunning one of the failed ones and it failed again. Based on the log, I'm seeing this error:

`Argument of type '"dark:hover:text-teal"' is not assignable to parameter of type 'TArg'.`

**Review by jst-cyr — CHANGES_REQUESTED** [review]
Notes on my latest review in dark mode:

1. Homepage looks great. Footer is black now in dark mode, though, which was not the case previously. Previously we used the same footer colour in dark mode as the dark charcoal right above it. I don't know if this is part of the new branding guidelines, but I'm mentioning it because it's not consistent with how we designed previously.
2. On `/contribute` the side nav in dark mode is using violet. Like other places, the contrast here doesn't work. Likely needs teal in dark mode. This also applies to other pages with the side nav component.
3. On `/learn` there is a strange behaviour with the 'arrow' for the Learning@Sitecore promo box near the bottom. In production, hovering over the arrow animates it to slide to the right. On the preview site, there is a strange hitch in the animation where it does a slight dip as it moves to the right.
4. Not critical: On many landing pages (like docs/community/discover) it appears as if spacing beneath the hero banner has changed. Production has less vertical spacing between the first segment of content and the hero banner. It does appear to be a lot of spacing. For some reason, pages like the product landing page (e.g. /content-management) don't have this issue.
5. The menu shows the 'current' section in "Desktop" view. The underline for the current section is teal, but the text is coloured violet. In Dark mode it should probably be both teal (the hover colour is correctly teal)

Overall looks really nice! Once we get a few of these knocked off, I'll do a final check in light mode.

**Comment by markvanaalst** [comment]
Fixed the color and padding issues. The footer on the corporate site changed to a lighter version but does not have a dark mode. Therefore inverted to color usage so we have a matching footer for our dark mode.

Could not reproduce the arrow issue on the [current preview site](https://developer-portal-9iwiks0p2-sitecoretechnicalmarketing.vercel.app/)

**Comment by jst-cyr** [comment]
No worries about the arrow. The padding looks better, even less than what we have on the production site. I am finding I'm not enjoying the new grey as much as the old one, this one has more of a 'green' tinge to it, but we can't control branding decisions here.

I'm going to take a look at the site quickly in dark mode again, and then look at it in light mode. One thing I noted, the "Suggest an Edit" button is not showing? Is that intended? Is the branch just behind?

**Review by jst-cyr — CHANGES_REQUESTED** [review]
Dark mode and light-mode look good! The only things I noticed"

1. The left-side nav (as seen on pages like: `/learn/integrations/xm-cdp`) appears to have a slightly larger font than in production. The font-sizes on the links are both 16 pixels and the line-heights are the same, but the font-family has changed so I'm guessing the new font is slightly larger typeset? Do we need to reduce the font-size to compensate? More of a question to you on how it looks
2. Suggest and Edit button missing (out of Sync with main?)
3. Background seems to have a 'green' tinge to it, not sure if that is intended?
4. GitHub shows there is a branch conflict that needs to be resolved

**Comment by markvanaalst** [comment]
Merged main into rebranding branch, resolved conflicts and refactored the edit button

**Comment by markvanaalst** [comment]
> The left-side nav (as seen on pages like: /learn/integrations/xm-cdp) appears to have a slightly larger font than in production. The font-sizes on the links are both 16 pixels and the line-heights are the same, but the font-family has changed so I'm guessing the new font is slightly larger typeset? Do we need to reduce the font-size to compensate? More of a question to you on how it looks

Paragraph font-size slightly reduced

> Background seems to have a 'green' tinge to it, not sure if that is intended?

Background colors are according to branding standards


Latest version now available on [preview](https://developer-portal-dgb2kbuvj-sitecoretechnicalmarketing.vercel.app/)

**Review by jst-cyr — APPROVED** [review]
Looks great! No conflicts showing, Suggest an Edit button is now showing, and text in the side nav seems to be closer to original size.

**Pull request merged**
