### PR TITLE
Migrate newsletter to markdown

### LINKED ISSUE #696: Application error: /newsletter/latest
Application error occurs while browsing the `/newsletter/latest` page. A PR is created for this issue. #697 

image

### LINKED ISSUE #703: March newsletter: Video link to Rob's video doesn't work
**URL:** https://developers.sitecore.com/newsletter/2024/03

Click on "Watch now" link for "Sitecore Search - Debugging Crawling Errors". It loads the image, not the video. Need to update the URL to the YouTube link.

### PR DESCRIPTION
**Pull request by markvanaalst**
## Description / Motivation
This PR adds two major changes:
- Newsletters are now stored using markdown (workaround for the serverless functions error during deployment + adds more flexibility for changing newsletter layout)
- Latest newsletter is now a client side redirect (Fixes #696 )
- Additional change that fixes #703 

(branch name is a bit misleading)

## How Has This Been Tested?
Local and [Vercel](https://developer-portal-ijihz8qpc-sitecoretechnicalmarketing.vercel.app/newsletter/)

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)

## Checklist:
- [ ] I have read the Contributing guide.
- [ ] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change.
- [ ] My change is a documentation change and there are NO other updates required.
- [ ] My change has new or updated images which are stored in the `/public/images` folder that need to be migrated to Sitecore DAM

### CODE REVIEW

**Comment by markvanaalst** [comment]
@jst-cyr could you do a review for the pages under this [path](https://developer-portal-ijihz8qpc-sitecoretechnicalmarketing.vercel.app/newsletter/)?

**Comment by markvanaalst** [comment]
Client side redirect fixes #696

**Review by jst-cyr — CHANGES_REQUESTED** [review]
The 'latest' redirect seems to be working with inline clicking, new tabs, and new windows, so that looks great!

I scanned through the individual newsletters and they all displayed correctly in the browser. I started finding some individual content issues so I'm going to keep that out of this review and we can fix those individually as we have time.

Issues discovered:
- [Newsletter home page](https://developer-portal-ijihz8qpc-sitecoretechnicalmarketing.vercel.app/newsletter): The newsletters are listed on the left starting with 2024, but in the main container are displayed starting with 2022. I think most recent makes sense, so we should list them as 2024 -> 2022
- [Year landing page](https://developer-portal-ijihz8qpc-sitecoretechnicalmarketing.vercel.app/newsletter/2024): Similarly, the individual year landing pages have the opposite order listing in the main content container.
- Side menu: There is no way to get back to the top page (other than the top menu). I expected the 'Archive' text to link me back, but it doesn't have a link.

**Review by jst-cyr — APPROVED** [review]
✅ Fix for Rob's video link in March 2024 confirmed.
✅ Latest issue link fix confirmed.
✅ Archive link allows user to go back to newsletter listing
✅ Newsletter 'years' listed chronologically reverse now
✅ Newsletter issues within year listed chronologically reverse now

**Pull request merged**
