### PR TITLE
Issue 106 - Add Sitecore Discover Content

### LINKED ISSUE #106: Add Reflektion Content to Site
We need to include Reflektion content to the various areas of the site where applicable.

### PR DESCRIPTION
**Pull request by robearlam**
Added content for Sitecore Discover product

## Description
Added Sitecore Discover to Solution & Product sections

Closes #106

### CODE REVIEW

**Review by jst-cyr — CHANGES_REQUESTED** [review]
**Menu**
I noticed that a new solution "Search" was added. I think we had been trying to align to Sitecore.com, and there it is called "Search and Merchandizing" to refer to Discover capabilities. That being said, for XC/OC we used 'Commerce' instead of Storefronts and Marketplaces, so I am wondering which approach we should go with:

1. Introduce 'Search and Merchandizing' (instead of just 'Search'), and update Commerce to 'Storefronts and Marketplaces' and align with sitecore.com, or
2. Move "Sitecore Discover" into the "Commerce" menu, or
3. Keep 'Search' as is, with the plan to move Sitecore Search in here later (which I'm not sure how people are going to categorize yet...)

**Sitecore Discover page**
Some notes:
1. Depending on what we do with the menu, the slug might change? On sitecore.com, they use /search-merchandizing, but if we go as a subset of commerce it might be commerce/discover?
2. The first introduction sentence feels very 'marketing'? Nothing worth blocking the merge on, but it would be good if there was a way to incorporate some of the tech keywords in here? Maybe something from the [Reflektion tech page](https://reflektion.com/technology/)?
3. There are 3 links to a Google spreadsheet, but for me they all open the spreadsheet at the top, not going to any specific section. It looks like you have a GUID in the URL, but it doesn't seem to do anything for me? (Chrome)

**Comment by robearlam** [comment]
So choosing the first option of aligning with Sitecore.com made the most sense to me, so I've changed the structure to 'Search and Merchandizing'  and  'Storefronts and Marketplaces'.

Looks like a copy/paste error I missed with that spreadsheet, so I've updated those to the correct links.

**Review by jst-cyr — CHANGES_REQUESTED** [review]
I like the move towards Search and Merdandizing/Storefronts and Marketplaces. Looks like some stuff is broken now by this flow. It may have been easier to move Search over to Commerce... we're going to have a lot of broken links, and we may need to incorporate some sort of redirect strategy for the old Commerce links (maybe some edge redirects?)

Other issues I noticed so far:
1. On the home page, there is still a 'Commerce' box, instead of Storefronts
2. Clicking on that box goes to the /commerce page, which has only OrderCloud and XC. Probably this needs to be refactored to Storefronts and Merchandizing.
3. On the homepage, there is no 'Search and Merchandizing' box
4. Clicking on the link in the Solution menu to go to the storefronts landing page gets a 404.
5. Product menu still goes to /commerce links for OrderCloud and XC.

**Comment by robearlam** [comment]
> I like the move towards Search and Merdandizing/Storefronts and Marketplaces. Looks like some stuff is broken now by this flow. It may have been easier to move Search over to Commerce... we're going to have a lot of broken links, and we may need to incorporate some sort of redirect strategy for the old Commerce links (maybe some edge redirects?)
> 
> Other issues I noticed so far:
> 
> 1. On the home page, there is still a 'Commerce' box, instead of Storefronts
> 2. Clicking on that box goes to the /commerce page, which has only OrderCloud and XC. Probably this needs to be refactored to Storefronts and Merchandizing.
> 3. On the homepage, there is no 'Search and Merchandizing' box
> 4. Clicking on the link in the Solution menu to go to the storefronts landing page gets a 404.
> 5. Product menu still goes to /commerce links for OrderCloud and XC.

Good spots, I've updated the homepage - it actually looks a bit more balanced with the new search box so that's a bonus! I also fixed the menu links and introduced the redirects for the old `/commerce` urls.

**Review by jst-cyr — CHANGES_REQUESTED** [review]
Looking really good! I agree the balance is better. The way you've done it the commerce-related ones show up near each other (stacked above each other), but it means 'DevOps' is technically sorted as a 'higher' item in the list than Search. We probably need to confer with Mark as to what our strategy for the menus should be as we add items.

Here are the issues I noticed:
1. On `/storefronts-and-marketplaces` we mention 'merchandising' (I think this is because of OrderCloud). This is somewhat confusing now that we have a separate Search and Merchandising section? Should we take out that reference? Or should we also link to OrderCloud from Search and Merchandizing?
2. If we keep it, on `/storefronts-and-marketplaces` we use an 's' for merchandising, but in the menu we use 'z' for merchandizing. On sitecore.com, they use the 'z', so we probably want to align to that.
3. On `/search-and-merchandizing/discover` we use 'merchandising' with an 's'. Probably should be the 'z' here.
4. On `/storefronts-and-marketplaces/experience-commerce` the 's' is used for merchandisers
5. If OrderCloud provides Merchandizing capabilities, we should add it to the Search and Merchandizing section for 'Solution'
6. Under the 'Product' menu, we list "Merchandizing" under Sitecore OrderCloud, but the link takes you to the Storefronts and Marketplaces URL. If there is Merchandizing capabilities, it should go to a separate URL for OrderCloud under `search-and-merchandizing`.
7. Same comment about XC in the 'Product' menu (lists Merchandizing in the text).

**Comment by robearlam** [comment]
> Looking really good! I agree the balance is better. The way you've done it the commerce-related ones show up near each other (stacked above each other), but it means 'DevOps' is technically sorted as a 'higher' item in the list than Search. We probably need to confer with Mark as to what our strategy for the menus should be as we add items.
> 
> Here are the issues I noticed:
> 
> 1. On `/storefronts-and-marketplaces` we mention 'merchandising' (I think this is because of OrderCloud). This is somewhat confusing now that we have a separate Search and Merchandising section? Should we take out that reference? Or should we also link to OrderCloud from Search and Merchandizing?
> 2. If we keep it, on `/storefronts-and-marketplaces` we use an 's' for merchandising, but in the menu we use 'z' for merchandizing. On sitecore.com, they use the 'z', so we probably want to align to that.
> 3. On `/search-and-merchandizing/discover` we use 'merchandising' with an 's'. Probably should be the 'z' here.
> 4. On `/storefronts-and-marketplaces/experience-commerce` the 's' is used for merchandisers
> 5. If OrderCloud provides Merchandizing capabilities, we should add it to the Search and Merchandizing section for 'Solution'
> 6. Under the 'Product' menu, we list "Merchandizing" under Sitecore OrderCloud, but the link takes you to the Storefronts and Marketplaces URL. If there is Merchandizing capabilities, it should go to a separate URL for OrderCloud under `search-and-merchandizing`.
> 7. Same comment about XC in the 'Product' menu (lists Merchandizing in the text).

Ok,, so I've fixed some of these up and it does look better

1. Remove this reference
2. Removed
3. Updated
4. Updated
5. Done

6 & 7 are more complicated. We now have both `Storefront & Marketplaces` and 'Search & Merchandising` showing both XC & OC as they both have features that fit under both. However this now means we have the same content shown under 2 URL's, its not really easy to split it out though as we don't have for example separate Merchandising vs Marketplace content specifically called out, they're just features that are available?

I don't think splitting the content between two locations makes sense as when someone views the OC page for example they would expect all of the OC content, so the question probably becomes "do we see any issue with having the same content available on two different URL's?"

**Comment by jst-cyr** [comment]
I've validated the changes made are good to go. **HOWEVER:**

> 6 & 7 are more complicated. We now have both `Storefront & Marketplaces` and `Search & Merchandising` showing both XC & OC as they both have features that fit under both. However this now means we have the same content shown under 2 URL's, its not really easy to split it out though as we don't have for example separate Merchandising vs Marketplace content specifically called out, they're just features that are available?
> 
> I don't think splitting the content between two locations makes sense as when someone views the OC page for example they would expect all of the OC content, so the question probably becomes "do we see any issue with having the same content available on two different URL's?"

This indicates to me that we have an issue with the structure then. If we are thinking about Search & Merchandizing as being separate from Storefronts and Marketplaces from an IA perspective, then we should have different pages about those capabilities (like we do with some of the other products). I agree that we shouldn't have the exact same page on two URLs. It should point to the appropriate docs that are for that specific concept. And then the product menu would have two links that take you to the different capabilities.

Or, we scrap this whole idea and go back to 'Commerce', have three products together, and we don't worry about trying to figure out the separation of these two concepts? I'm not sure a developer is going to be able to figure out going to Search and Merchandizing, landing on an OrderCloud page, and it's not specific to merchandizing?

Or, we stop talking about Merchandizing for OrderCloud and XC, and assume that from a solution perspective if you are interested in merchandizing you are really talking about Discover?

Might need a call for this.

**Comment by robearlam** [comment]
As discussed, this has now been changed to move XC, OC & Discover to all live under the 'Commerce' solution.

**Review by markvanaalst — APPROVED** [review]
Looks good to me!

**Pull request merged**
