### PR TITLE
Configured community questions for solution pages

### PR DESCRIPTION
**Pull request by markvanaalst**
## Description
Configured the solution pages to show the latest questions (if available) from their respective sub forums on Sitecore Community 

## Motivation
Community integration was only used on homepage and community page. Solution pages where still a todo.

## How Has This Been Tested?
Local testing and Vercel preview environment

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)

## Checklist:
- [X] I have read the Contributing guide.
- [X] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change.
- [X] My change is a documentation change and there are NO other updates required.
- [ ] My change is a documentation change and it requires an update to the navigation.
- [ ] My change has new or updated images which are stored in the `/public/images` folder that need to be migrated to Sitecore DAM

### CODE REVIEW

**Review by jst-cyr — CHANGES_REQUESTED** [review]
In general, I'm not sure mapping to a forum/category is going to work long term. I think the topics are going to possibly be more granular, as the categories right now are really high-level and don't get into the details of the tech. However, I'm reviewing based on the approach implemented. I have only reviewed the Product menu pages because I had a lot of commentary and I think resolving these will impact feedback for solution landing pages as they tend to be a rollup.

This also means I have not reviewed the DevOps pages (other that Developer Collection) as they are not in the Product menu.

**Content Hub testing**
The first place I tested was the Content Hub links under Product. Community content showed (one) on the DAM page: `dam-and-content-operations/dam` However, the other two (Experience Edge and Content Hub) did not show any content. From what I can tell from the files changed, this is because there is nothing posted in the Content Hub forum. However, it does not look like the Experience Edge page was configured to show the community integration at all and I see no relevant forum on Community. 

- We probably need a 'headless' or similar forum for questions around Edge, GraphQL, Vercel, etc. ? And then tie this to Edge and other 'headless tech' pages?

**Personalize and CDP**
I then tested **Personalize** and **CDP** pages. Issues noticed:
- Neither show community posts, even though there are personalization posts.
- Personalize should be configured for Personalization and Testing forum, not customer data management.
- From the files changed I only see a change for Personalize and the Customer Data Management landing page, but not the CDP page. CDP Page should be configured to look at the Customer Data Management forum. (Even though there is currently no content to show)

**XM**
Next section was XM which has 5 pages (Content Management - XM, Edge for XM, Headless Services, SXA, Dev Collection). None of these pages have been configured to display forums.

- Content Management - XM (`/content-management/experience-manager`) should be mapped to content management forum (as was done for the parent page)
- If we can create a new Headless forum, we should likely map Headless and Edge to that, but they don't exist now so we can't do that yet.
- Dev Collection has no relevant forum, and tagging with Content Management seems to be too wide a net to cast. We need a DevOps forum or something that can catch things like Managed Cloud, Sitecore CLI, TDS, Docker, etc.

**XP**
All three pages here seem to be tagged to Experience Platform category and are all pulling data. Not exactly relevant to the context of the pages, though? Given these are for marketing automation, personalization, and customer data management. However, technically working as configured.

**Moosend**
Moosend page shows no community posts and does not appear to be configured for a category.

- I suggest tagging in the 'marketing automation' category used by the parent landing page. That forum is currently empty, but seems to be the correct one to map to.

**OrderCloud**
No posts shown, and it doesn't look like this page has been configured (`/commerce/ordercloud`). I would expect 'Order management' and 'storefronts and marketplaces' to be tagged. Possibly even search and merchandizing.

**XC**
The XC page shows no posts and is not configured (`/commerce/experience-commerce`). I would expect 'Order management' and 'storefronts and marketplaces' to be tagged. Possibly even search and merchandizing.

NOTE: This is the same feedback as OrderCloud, and if done the same for both we'll have the same listings on both pages. That seems wrong? I feel like we would want XC questions to show on the XC page and OrderCloud questions to show on the OC page.

**Discover**
The Discover page (`commerce/discover`) shows no posts and does not seem to be configured. I would expect 'searchAndMerchandizing' to be tagged here (there is one post in that forum, but it is about SXA search).

**Comment by jst-cyr** [comment]
Just a note that I reran one of the checks which failed on the deploy. All checks are now passed. Will now take a look at the build.

**Review by jst-cyr — CHANGES_REQUESTED** [review]
Hey Mark, I've reviewed the latest commit. All product pages that were previously reviewed seem to now be configured to pull from the most appropriate forums that exist. 

NOTE: I still feel like this is not the right solution, but it is the right solution for now. Having an SXA Search question showing on the XC, Commerce, and Discover pages does not seem to be what we would intend for a developer looking to see questions about those different products.

**DAM and Content Operations Solution page**
The page `/dam-and-content-operations` appears to be configured to pull from `contentOperations` forum and `digitalAssetManagement`. According to the Community Forum there is a post in the DAM forum: https://community.sitecore.com/community?id=community_forum&sys_id=d27d271d1b16f050486a4083b24bcbdf

However, this post does not display on the Vercel review site on the solution landing page.

The DAM product page (`/dam-and-content-operations/dam`) appears to be configured in the code to pull from digitalAssetManagement, and it does show the correct post.


**Customer Data Management solution page**
This page appears to be correctly configured with `['customerDataManagement', 'experiencePlatform']`. However, no forum questions are shown, even though there are questions in the XP forum. Seems to be a similar issue where only the first forum is shown?

**NOTE:** I just noticed an issue while testing the Commerce solution page which may explain this. It looks like the component is pre-filtered to the first configured forum. I think the component is hiding itself if there are 'zero' results, even if there are results in the other forum?

**Commerce solution page**
This solution page seems to be displaying the configured forums correctly, but I think Order Management is missing?

Also, I did not expect it to be pre-filtered. As a user, since I had not selected a filter, I expected to see everything?

** Personalization and Testing solution page**
When I first tested this I thought it was fine until I hit the Commerce page and realized there was default filtering on the component. When I came back I tried toggling the filter by. When I selected to filter by "Customer Data Management" there were XP questions shown. When I filtered by XP, nothing was shown.

**Comment by markvanaalst** [comment]
Was blocked due to #231. Merging now

**Pull request merged**
