### PR TITLE
309 create product page for xm cloud

### LINKED ISSUE #309: Create product page for XM Cloud
A new page is required to hold initial XM Cloud information. Changes required:

1. Top level Solution menu should have an XM Cloud option under 'Content management and Delivery'
2. Top level Product menu should have an XM Cloud option. This option should have a submenu option for content management link that also goes to the product page (same as the header). Similar setup as 'Discover'.  We can also add Edge and Headless Services options too, if that makes sense.
3. The [content management landing page](https://developers.sitecore.com/content-management) should have an option for XM Cloud.
4. On the [Learn page](https://developers.sitecore.com/learn) there should be a new "XM Cloud" examples box that links to the new Demo (if available on GitHub) and the XM Cloud Introduction project and the Headless SXA Starter kit that is used in the Portal
5. The XM Cloud page should be configured to show the [XM Cloud playlist](https://www.youtube.com/playlist?list=PL1jJVFm_lGnzqYagW1UahIBeqTIYSBQMc)
6. The XM Cloud page should be configured to show the [XM-cloud](https://sitecore.stackexchange.com/questions/tagged/xm-cloud) tag from Sitecore StackExchange
7. The XM Cloud page should have an introductory paragraph similar to other product pages.
8. The XM Cloud page should point to the [XM Cloud introduction page](https://developers.sitecore.com/learn/getting-started/xm-cloud-introduction)
9. The XM Cloud page should point to the same example repos added to the Learn page.
10. The XM Cloud page should contain as many relevant resources from the XM Cloud Introduction that should be 'Learn' resources for devs

### PR DESCRIPTION
**Pull request by jst-cyr**
## Description / Motivation
With the launch of XM Cloud, we need a page to hold all developer content and resources for people looking for information about the product. There is an XM Cloud Introduction article, but we need to have an official product resources page as well. This pull request is to add the necessary navigation and markdown partials to create that page, though some content needs GA before being able to be updated (like Docs links and Learning courses)

Additional work will be needed for these pages to be fully complete, but this should be good enough for a first launch and then we can iterate.

Fixes #309  

## How Has This Been Tested?

Tested locally and on Vercel preview environments.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)

## Checklist:
- [X] I have read the Contributing guide.
- [X] My code/comments/docs fully adhere to the Code of Conduct.
- [X] My change is a code change.
- [ ] My change is a documentation change and there are NO other updates required.
- [ ] My change has new or updated images which are stored in the `/public/images` folder that need to be migrated to Sitecore DAM

### CODE REVIEW

**Comment by markvanaalst** [comment]
#### 📝 Changed routes:


| [**/learn**](https://developer-portal-do56ezf7o-sitecoretechnicalmarketing.vercel.app/learn) |
|:-:|
|<a href="https://developer-portal-do56ezf7o-sitecoretechnicalmarketing.vercel.app/learn">Screenshot of /learn</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/_9uCIzFDZv6CRSKhmwFjgVS2tW3rvzWyayBbC9kH4W4ZoJmVoWETvFpA08F0QW1uaYanziJkttoVdxmPELw1pg.png">(view full size)</a> |







Commit e96be29e481d05c665d9313f1e8d58a9e7cc53a3 (https://developer-portal-do56ezf7o-sitecoretechnicalmarketing.vercel.app).

**Comment by markvanaalst** [comment]
Looks good! 

One minor thing; The XM Cloud product page seems to have some [TBD links](https://developer-portal-do56ezf7o-sitecoretechnicalmarketing.vercel.app/content-management/xm-cloud#documentation). I wasn't sure whether the documentation is already live and "linkable".

**Comment by jst-cyr** [comment]
@markvanaalst : The docs aren't available publicly yet. I think you need VPN or a password to get onto them. I could update the 'TBD' to have the same text as the 'Coming soon'? that is used for the training section?

Also, what do you think about the "Access the Portal" section? Should that link just be moved into Getting Started? I tried to replicate the idea of the 'Downloads' section, but it feels wrong.

**Review by markvanaalst — APPROVED** [review]

**Comment by markvanaalst** [comment]
For me getting started is more about "enablement". I think a separate link to access the portal is the right thing to do.

**Pull request merged**
