### PR TITLE
Issues/305 show current newsletter

### LINKED ISSUE #305: Show current page in left-nav
**NOTE:** Reported by documentation team member

> Quick observation about this page https://developers.sitecore.com/newsletter/2022/01. For me, it would be really useful if the bubble to the left of the month was highlighted when I had that newsletter selected. 

Essentially, some sort of styling to show which page you are on in the left-nav of a multi-page navigation.

### PR DESCRIPTION
**Pull request by markvanaalst**
## Description / Motivation

Highlights newsletter that is currently viewed.
Fixes #305 

## How Has This Been Tested?

Local and [Vercel](https://developer-portal-oj62d5iwk-sitecoretechnicalmarketing.vercel.app/newsletter/2022/06)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)

## Checklist:

- [X] I have read the Contributing guide.
- [X] My code/comments/docs fully adhere to the Code of Conduct.
- [X] My change is a code change.
- [ ] My change is a documentation change and there are NO other updates required.
- [ ] My change has new or updated images which are stored in the `/public/images` folder that need to be migrated to Sitecore DAM

### CODE REVIEW

**Comment by markvanaalst** [comment]
#### 📝 Changed routes:


| [**…sletter/\[year\]/\[month\]**](https://developer-portal-2pukl12dz-sitecoretechnicalmarketing.vercel.app/newsletter/[year]/[month]) |
|:-:|
|<a href="https://developer-portal-2pukl12dz-sitecoretechnicalmarketing.vercel.app/newsletter/[year]/[month]">Screenshot of /newsletter/[year]/[month]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/N8nzI3DFt32dICieNIHigj7RYcZ552bj3nDBdseCGisgAiV1RtG07yFrFkW52wo6j_2wWXaenSRqL_bxpoIlTQ.png">(view full size)</a> |







Commit 4b5ffecdaf40c6a469fb8ad5b23b2ae51928374d (https://developer-portal-2pukl12dz-sitecoretechnicalmarketing.vercel.app).

**Review by jst-cyr — CHANGES_REQUESTED** [review]
The newsletter looks good, all the links work. One comment: The Standard Values Podcast link says "Read more", this should probably be "Watch now" instead.

**Comment by markvanaalst** [comment]
Update that specific [newsletter entry](https://developer-portal-k8d8f7o3d-sitecoretechnicalmarketing.vercel.app/newsletter/2022/06):

**Review by jst-cyr — APPROVED** [review]
Looks good!

**Pull request merged**
