### PR TITLE
Feature/suggest an edit

### LINKED ISSUE #222: Add deep link "edit this page" button to all pages
We should add an "Edit this page" type button on all pages, that deep links to create a PR on the repo referencing the file that needs to change, making it as simple as possible.

They have this feature already on the OC Docs, you can for example see it here: https://ordercloud.io/learn/ordercloud-basics/conventions

This would make it a lot simpler for contributors to make content update suggestions without having to clone & understand the repo.

### PR DESCRIPTION
**Pull request by markvanaalst**
## Description
Implemented "Suggest an edit' functionality for the pages that are driven by markdown files. Underneath each partial an edit button is rendered that links to the GitHub editor. Each page has an edit button in the footer when the page has a markdown file.

The edit process on GitHub is different for the types of users.
- Project admins can commit to main or create a PR
- Project editors can create a PR
- Other users need to fork the repo first and then create a PR

## Motivation
Fixes #222 - Allows for quicker feedback on content

## How Has This Been Tested?
Tested locally and on [Vercel environment](https://developer-portal-nz35bdioh-sitecoretechnicalmarketing.vercel.app/)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)

## Checklist:
- [X] I have read the Contributing guide.
- [X] My code/comments/docs fully adhere to the Code of Conduct.
- [X] My change is a code change.
- [ ] My change is a documentation change and there are NO other updates required.
- [ ] My change is a documentation change and it requires an update to the navigation.
- [ ] My change has new or updated images which are stored in the `/public/images` folder that need to be migrated to Sitecore DAM

### CODE REVIEW

**Comment by markvanaalst** [comment]
@robearlam @jst-cyr Could you both have a look and let me know what you think of it

@robearlam I don't think implementing this functionality requires us to make changes in security on the project. But I would appreciate your input on this.

**Review by robearlam — COMMENTED** [review]
I like the approach, a couple of things stand out for me though.....

- Do we need to have the footer (page) link and also the content (partial) link? It's a bit confusing as I only saw the footer link first and the other didn't stand out to me. Realistically most people are going to be suggesting changes to the content and not the meta data? - If you checkout one of the Integration Blueprints you'll see what I mean.

- Learn, Discover, community pages are missing their content edit link?

From a security prospective, we shouldn't have to change anything AFAIK. GitHub already manages whether you have write permissions and will even auto Fork then PR if you don't, which is pretty cool. (You can test by clicking an edit link to a repo you don't have access to, e.g the button on this page for me: https://ordercloud.io/learn/ordercloud-basics/conventions)

**Comment by markvanaalst** [comment]
> * Do we need to have the footer (page) link and also the content (partial) link? It's a bit confusing as I only saw the footer link first and the other didn't stand out to me. Realistically most people are going to be suggesting changes to the content and not the meta data? - If you checkout one of the Integration Blueprints you'll see what I mean.
Agree, it doesn't really make sense to have the metadata editable.

> * Learn, Discover, community pages are missing their content edit link?
Community doesn't have any markdown content, just components. For the discover and learn page it would mean each box would have an edit link. I wasn't really sure if it made sense to have these editable as it is just a list of links.

**Review by robearlam — APPROVED** [review]
Looks good now 👍

**Pull request merged**
